# Generated by Django 3.2.7 on 2021-09-26 20:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JogoCaregoria',
            new_name='JogoCategoria',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 26, 20, 36, 27, 594114)),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 26, 20, 36, 27, 594133)),
        ),
    ]
